language: python

install:
  - deactivate
  # Sets up a MINIConda enviroment in the name of the selected python version
  - source devtools/ci/install.sh
  # Do not buffer output of python outputs but flush them directly to the terminal
  - export PYTHONUNBUFFERED=true

script:
  - python --version
  - echo travis_fold:start:conda.build.package
  - conda install --yes conda-build
  - conda build devtools/conda-recipe
  - echo travis_fold:end:conda.build.package

  # Run tests in _test environment
  - conda create --yes --name test --use-local openpathsampling-dev
  - conda info --envs
  - source activate test
  - conda install --yes future
  - conda install --yes jupyter nose nose-timer python-coveralls msmbuilder pyemma #ipynbtest
  # - conda update --all --yes --use-local
  - source devtools/ci/git_hash.sh
  - source devtools/ci/nosetests.sh
  - if [ ${CONDA_PY:0:1} -eq "2" ]; then conda install --yes ipynbtest; source devtools/ci/ipythontests.sh; fi
  #- source devtools/ci/ipythontests.sh

  # Upload new docs
  - bash -x devtools/ci/after_sucess.sh

addons:
  apt:
    packages:
    - pandoc

env:
    - CONDA_PY=2.7  CONDA_NPY=1.10
    - CONDA_PY=3.6  CONDA_NPY=1.10

global:
  - secure: "NJvoSrLNd2ZR3HluJjEqI36gD5lsucwIvgnYjNmM4cwnnA77aLV9FRYTwlLRZn3XY9FL8KOzL5l0amNzMD7sQrf7bWwWv7iCUBddH549q9RSgiuOugtodYJ6VaXi76hk1rOgcJpDoCj9wTCIlMtWibPUzr1QHmdihfdM2iA2kkE="
  - secure: "l9NJkZDD0ALhkErUvhRrreLsrcWErd+CXpWv8dxHGtkjemNx6CwVtyL+a30jz/QwMANSZbKll/cPK5yJQvuwDaWxja6UPLLKVNGtma+CmwKcIC/wwTwbMoxcS62fyLJ3kS0qR8oCQz2nCPKiYyRGADtPLWVMZckY1SJfNYcKuCM="

  - secure: kb37xmsSV3pEnESnINzwlW2Cju/UFzA/G+m+NsihAwO8RMPZwKCrZK/rptgkUDACXJxom5M690WEukQkHnOt+OTrWhu7WKZgYeVuWUs2++RohYv/m5npaOHMMn+uYmF328v4PvPmXxbD02zzg5Tgdn82x8oa6J8BKX8ohOQ6Xpg=
